services:
  database:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mediscreen
  patients:
    image: mediscreen-patients:1.0.0
    ports:
      - 8081:8081
    depends_on:
      - database
  reports:
    image: mediscreen-reports:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - patients
      - records
  records:
    image: mediscreen-records:1.0.0
    ports:
      - 8082:8082

volumes:
    database-volume: